module alchemy_ai {
    requires langchain4j;
    requires langchain4j.core;
    requires langchain4j.open.ai;
    requires langchain4j.community.dashscope;
    requires langgraph4j.core;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.databind;
    requires org.jspecify;
    requires java.logging;
    requires java.net.http;

    // 领域模型对运行时反射开放（infra 层 JDBI 映射 Bean）
    opens athena.coder.entity;
    opens athena.coder.entity.chat;
    opens athena.coder.entity.model;
    opens athena.coder.entity.tree;

    opens athena.coder.ai.tool to langchain4j;
    opens athena.coder.ai.assistant.agent.result to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.user to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.router to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.confirm to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.planner to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.coder to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.debugger to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.reviewer to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.tester to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;
    opens athena.coder.ai.assistant.agent.result.summarizer to com.fasterxml.jackson.databind, langchain4j, langchain4j.core;

    exports athena.coder.ai.assistant.agent;
    exports athena.coder.ai.assistant.agent.code;
    exports athena.coder.ai.assistant.agent.debug;
    exports athena.coder.ai.assistant.agent.result;
    exports athena.coder.ai.assistant.agent.result.coder;
    exports athena.coder.ai.assistant.agent.result.confirm;
    exports athena.coder.ai.assistant.agent.result.debugger;
    exports athena.coder.ai.assistant.agent.result.planner;
    exports athena.coder.ai.assistant.agent.result.reviewer;
    exports athena.coder.ai.assistant.agent.result.router;
    exports athena.coder.ai.assistant.agent.result.summarizer;
    exports athena.coder.ai.assistant.agent.result.tester;
    exports athena.coder.ai.assistant.agent.result.user;
    exports athena.coder.ai.assistant.agent.test;
    exports athena.coder.ai.assistant.agent.word;
    exports athena.coder.ai.assistant.model;
    exports athena.coder.ai.assistant.model.factory;
    exports athena.coder.ai.rag;
    exports athena.coder.ai.rag.model;
    exports athena.coder.ai.spi;
    exports athena.coder.ai.tool;
    exports athena.coder.ai.tool.analyzer;
    exports athena.coder.ai.tool.base;
    exports athena.coder.ai.tool.cache;
    exports athena.coder.ai.tool.config;
    exports athena.coder.ai.tool.dependency;
    exports athena.coder.ai.tool.exception;
    exports athena.coder.ai.tool.executor;
    exports athena.coder.ai.tool.security;
    exports athena.coder.ai.tool.strategy;
    exports athena.coder.ai.tool.util;
    exports athena.coder.ai.tool.validation;
    exports athena.coder.ai.util;
    exports athena.coder.ai.workflow;
    exports athena.coder.ai.workflow.entity;
    exports athena.coder.ai.workflow.gate;
    exports athena.coder.ai.workflow.node;
    exports athena.coder.ai.workflow.node.code;
    exports athena.coder.ai.workflow.node.debug;
    exports athena.coder.ai.workflow.node.test;
    exports athena.coder.ai.workflow.node.word;
    exports athena.coder.ai.workflow.report;
    exports athena.coder.ai.workflow.workflow;
    exports athena.coder.entity;
    exports athena.coder.entity.chat;
    exports athena.coder.entity.model;
    exports athena.coder.entity.tree;
    exports athena.coder.exception;
}
